<?php

/**
 * AFFILIATE_BOOSTER_Config.
 *
 * @package AFFILIATE
 */
if (!class_exists('AFFILIATE_BOOSTER_Config')) {

    /**
     * Class AFFILIATE_BOOSTER_Config.
     */
    class AFFILIATE_BOOSTER_Config
    {

        /**
         * 
         * Block Attributes
         *
         * @var block_attributes
         */
        public static $block_attributes = null;

        /**
         * Block Assets
         *
         * @var block_attributes
         */
        public static $block_assets = null;

        /**
         * Get Widget List.
         *
         * @since 0.0.1
         *
         * @return array The Widget List.
         */
        public static function get_block_attributes()
        {

            if (null === self::$block_attributes) {
                self::$block_attributes = array(
                    'affiliate-booster/propsandcons' => array(
                        'slug' => '',
                        'title' => __('Prop Cons', AFB_DOMAIN),
                        'description' => __('Showcase Post title', AFB_DOMAIN),
                        'default' => true,
                        'attributes' => array(
                            'block_id' => '',
                            'propsTitle' => '',
                            'titleLoadGoogleFonts' => '',
                            'consTitle' => '',
                            'recreateStyles' => '',
                            'alignment' => '',
                            'listType' => '',
                            'bulletStyle' => '',
                            'bulletStyleTwo' => '',
                            'numberCorner' => '',
                            'numberFontSize' => '',
                            'numberBgSize' => '',
                            'useNumberBg' => '',
                            'numberBg' => '',
                            'numberBgHover' => '',
                            'titleBgColor' => '',
                            'titleTextColor' => '',
                            'titlefontFamily' => '',
                            'titlefontWeight' => '900',
                            'titlefontSubset' => '',
                            'titlefontSizeType' => 'px',
                            'titlefontSizeTypeMobile' => 'px',
                            'titlefontSizeTypeTablet' => 'px',
                            'titlefontSizeDesktop' => '20',
                            'titlefontSizeMobile' => '',
                            'titlefontSizeTablet' => '',
                            'titlelineHeight' => ' ',
                            'titlelineHeightMobile' => '',
                            'titlelineHeightTablet' => '',
                            'titleletterSpacing' => '',
                            'titleletterSpacingMobile' => '',
                            'titleletterSpacingTablet' => '',
                            'titleletterSpacingType' => '',
                            'titleletterSpacingTypeTablet' => '',
                            'titleletterSpacingTypeMobile' => '',
                            'titletextTransform' => '',
                            'titletextDecoration' => '',
                            'titlefontStyle' => '',
                            'listfontFamily' => '',
                            'listfontWeight' => '',
                            'listfontSubset' => '',
                            'listfontSizeType' => 'px',
                            'listfontSizeTypeMobile' => 'px',
                            'listfontSizeTypeTablet' => 'px',
                            'listfontSizeDesktop' => '',
                            'listfontSizeMobile' => '',
                            'listfontSizeTablet' => '',
                            'listlineHeight' => '',
                            'listlineHeightMobile' => '',
                            'listlineHeightTablet' => '',
                            'listletterSpacing' => '',
                            'listletterSpacingMobile' => '',
                            'listletterSpacingTablet' => '',
                            'listletterSpacingType' => 'px',
                            'listletterSpacingTypeTablet' => 'px',
                            'listletterSpacingTypeMobile' => 'px',
                            'listtextTransform' => '',
                            'listtextDecoration' => '',
                            'listfontStyle' => '',
                            'listTextColor' => '',
                            'propsBgColor' => '',
                            'propsTextColor' => '',
                            'propsIconColor' => '#30ac3d',
                            'consBgColor' => '',
                            'consTextColor' => '',
                            'consIconColor' => '#ff1818',
                            'consListColor' => '',
                            'propsListColor' => '',
                            'titleTag1' => 'p',
                            'titleTag2' => 'p',
                            'boxShadow' => [
                                'openShadow' => true, 'blur' => 35, 'color' => "rgba(0, 0, 0, 0.14)", 'horizontal' => 0,
                                'inset' => '', 'spread' => 0, 'vertical' => 8
                            ],
                        ),
                    ),
                    'affiliate-booster/ab-single-product' => array(
                        'slug' => '',
                        'title' => __('Single Product', AFB_DOMAIN),
                        'description' => __('Showcase Post title', AFB_DOMAIN),
                        'default' => true,
                        'attributes' => array(
                            'block_id' => '',
                            'boxBg' => ['openBg' => false],
                            'btnBg' => ['openBg' => false],
                            'btnBgHover' => ['openBg' => false],
                            'btnShadow' => [
                                'openShadow' => true, 'blur' => 35, 'color' => "rgba(0, 0, 0, 0.14)", 'horizontal' => 0,
                                'inset' => '', 'spread' => 0, 'vertical' => 8
                            ],
                            'spTitle' => '',
                            'spSubTitle' => '',
                            'titleLoadGoogleFonts' => '',
                            'spBtnText' => '',
                            'spContent' => '',
                            'spBtnHref' => '',
                            'titleTextColor' => '',
                            'titlefontFamily' => '',
                            'titlefontWeight' => '900',
                            'titlefontSubset' => '',
                            'titlefontSizeType' => 'px',
                            'titlefontSizeTypeMobile' => 'px',
                            'titlefontSizeTypeTablet' => 'px',
                            'titlefontSizeDesktop' => '32',
                            'titlefontSizeMobile' => '',
                            'titlefontSizeTablet' => '',
                            'titlelineHeight' => '',
                            'titlelineHeightMobile' => '',
                            'titlelineHeightTablet' => '',
                            'titleletterSpacing' => '',
                            'titleletterSpacingMobile' => '',
                            'titleletterSpacingTablet' => '',
                            'titleletterSpacingType' => 'px',
                            'titleletterSpacingTypeTablet' => 'px',
                            'titleletterSpacingTypeMobile' => 'px',
                            'titletextTransform' => '',
                            'titletextDecoration' => '',
                            'titlefontStyle' => '',
                            'btnLoadGoogleFonts' => '',
                            'btnfontFamily' => '',
                            'btnfontWeight' => '',
                            'btnfontSubset' => '',
                            'btnfontSizeType' => 'px',
                            'btnfontSizeTypeMobile' => 'px',
                            'btnfontSizeTypeTablet' => 'px',
                            'btnfontSizeDesktop' => '',
                            'btnfontSizeMobile' => '',
                            'btnfontSizeTablet' => '',
                            'btnlineHeight' => '',
                            'btnlineHeightMobile' => '',
                            'btnlineHeightTablet' => '',
                            'btnletterSpacing' => '',
                            'btnletterSpacingMobile' => '',
                            'btnletterSpacingTablet' => '',
                            'btnletterSpacingType' => 'px',
                            'btnletterSpacingTypeTablet' => 'px',
                            'btnletterSpacingTypeMobile' => 'px',
                            'btntextTransform' => '',
                            'btntextDecoration' => '',
                            'btnfontStyle' => '',
                            'btnBgColor' => '#F9CC29',
                            'btnHoverBgColor' => '#00ffcc',
                            'btnTextColor' => '#000000',
                            'btnTextHoverColor' => '#000000',
                            'btnBorderColor' => '#F9CC29',
                            'btnBorderHoverColor' => '#F9CC29',
                            'btn_Htarget' => '',
                            'cntnLoadGoogleFonts' => '',
                            'cntnfontFamily' => '',
                            'cntnfontWeight' => '',
                            'cntnfontSubset' => '',
                            'cntnfontSizeType' => 'px',
                            'cntnfontSizeTypeMobile' => 'px',
                            'cntnfontSizeTypeTablet' => 'px',
                            'cntnfontSizeDesktop' => '',
                            'cntnfontSizeMobile' => '',
                            'cntnfontSizeTablet' => '',
                            'cntnlineHeight' => '',
                            'cntnlineHeightMobile' => '',
                            'cntnlineHeightTablet' => '',
                            'cntnletterSpacing' => '',
                            'cntnletterSpacingMobile' => '',
                            'cntnletterSpacingTablet' => '',
                            'cntnletterSpacingType' => 'px',
                            'cntnletterSpacingTypeTablet' => 'px',
                            'cntnletterSpacingTypeMobile' => 'px',
                            'cntntextTransform' => '',
                            'cntntextDecoration' => '',
                            'cntnfontStyle' => '',
                            'cntnTextColor' => '',
                            'iconColor' => '#30ac3d',
                            'boxPadding' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxPaddingMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxPaddingTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxMargin' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxMarginMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxMarginTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxAlignment' => '',
                            'boxAlignmentMobile' => '',
                            'boxAlignmentTablet' => '',
                            'boxBackgroundColor' => '#ffffff',
                            'image' => '',
                            'subtitleLoadGoogleFonts' => '',
                            'subtitleTextColor' => '',
                            'subtitlefontFamily' => '',
                            'subtitlefontWeight' => '900',
                            'subtitlefontSubset' => '',
                            'subtitlefontSizeType' => 'px',
                            'subtitlefontSizeTypeMobile' => 'px',
                            'subtitlefontSizeTypeTablet' => 'px',
                            'subtitlefontSizeDesktop' => '28',
                            'subtitlefontSizeMobile' => '',
                            'subtitlefontSizeTablet' => '',
                            'subtitlelineHeight' => '',
                            'subtitlelineHeightMobile' => '',
                            'subtitlelineHeightTablet' => '',
                            'subtitleletterSpacing' => '',
                            'subtitleletterSpacingMobile' => '',
                            'subtitleletterSpacingTablet' => '',
                            'subtitleletterSpacingType' => 'px',
                            'subtitleletterSpacingTypeTablet' => 'px',
                            'subtitleletterSpacingTypeMobile' => 'px',
                            'subtitletextTransform' => '',
                            'subtitletextDecoration' => '',
                            'subtitlefontStyle' => '',
                            'spSubTitleColor' => '',
                            'boxBorderType' => '',
                            'boxBorderColor' => '#006fbf',
                            'boxBorderWidth' => ['top' => 8, 'right' => 8, 'bottom' => 8, 'left' => 8, 'unit' => 'px'],
                            'boxShadow' => [
                                'openShadow' => true, 'blur' => 35, 'color' => "rgba(0, 0, 0, 0.14)", 'horizontal' => 0,
                                'inset' => '', 'spread' => 0, 'vertical' => 8
                            ],
                            'subtitleAlignment' => 'left',
                            'subtitleAlignmentMobile' => 'center',
                            'subtitleAlignmentTablet' => 'left',
                            'titleAlignment' => 'center',
                            'titleAlignmentMobile' => 'center',
                            'titleAlignmentTablet' => 'center',
                            'cntnAlignment' => 'left',
                            'cntnAlignmentMobile' => '',
                            'cntnAlignmentTablet' => '',
                            'btnBorderType' => '',
                            'btnBorder' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderRadius' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderRadiusTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderRadiusMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnPadding' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnPaddingMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnPaddingTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnMargin' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnMarginMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnMarginTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'imagePadding'  => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'imagePaddingMobile'  => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'imagePaddingTablet'  => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'customImgWidth' => '',
                            'customImgWidthMobile' => '',
                            'customImgWidthTablet' => '',
                            'titleTag1' => 'p',
                            'titleTag2' => 'p',
                        ),
                    ),
                    'affiliate-booster/ab-star-rating' => array(
                        'slug' => '',
                        'title' => __('AB Star Rating', AFB_DOMAIN),
                        'description' => __('Showcase Star Rating', AFB_DOMAIN),
                        'default' => true,
                        'attributes'  => array(
                            'block_id' => '',
                            'starsSize' => 20,
                            'titleTag1' => 'p',
                            'titleTag2' => 'p',
                            'starsSizeMobile' => 20,
                            'starsSizeTablet' => 20,
                            'ratings' => '',
                            'ratingsColor' => '#ffa500',
                            'ratingsSpacing' => '',
                            'ratingsSize' => 20,
                            'ratingsSizeMobile' => 20,
                            'ratingsSizeTablet' => 20,
                            'selectedStars' => 20,
                            'ratingAlignemt' =>  '',
                            'ratingAlignemtMobile'=>  '',
                            'ratingAlignemtTablet'=>  '',
                            'itemPadding'       => '',
                            'itemPaddingMobile' => '',
                            'itemPaddingTablet' => '',
                        ),
                    ),
                    'affiliate-booster/ab-notice-box' => array(
                        'slug' => '',
                        'title' => __('Notice Box', AFB_DOMAIN),
                        'description' => __('Showcase Notice', AFB_DOMAIN),
                        'default' => true,
                        'attributes' => array(
                            'block_id' => '',
                            'noticeTitle' => '',
                            'iconColor' => '#30ac3d',
                            'titleLoadGoogleFonts' => '',
                            'noticeContent' => '',
                            'titleTextColor' => '',
                            'titleTag1' => 'p',
                            'titleTag2' => 'p',
                            'titlefontFamily' => '',
                            'titlefontWeight' => '900',
                            'titlefontSubset' => '',
                            'titlefontSizeType' => 'px',
                            'titlefontSizeTypeMobile' => 'px',
                            'titlefontSizeTypeTablet' => 'px',
                            'titlefontSizeDesktop' => '20',
                            'titlefontSizeMobile' => '',
                            'titlefontSizeTablet' => '',
                            'titlelineHeight' => '',
                            'titlelineHeightMobile' => '',
                            'titlelineHeightTablet' => '',
                            'titleletterSpacing' => '',
                            'titleletterSpacingMobile' => '',
                            'titleletterSpacingTablet' => '',
                            'titleletterSpacingType' => 'px',
                            'titleletterSpacingTypeTablet' => 'px',
                            'titleletterSpacingTypeMobile' => 'px',
                            'titletextTransform' => '',
                            'titletextDecoration' => '',
                            'titlefontStyle' => '',
                            'cntnLoadGoogleFonts' => '',
                            'cntnfontFamily' => '',
                            'cntnfontWeight' => '',
                            'cntnfontSubset' => '',
                            'cntnfontSizeType' => 'px',
                            'cntnfontSizeTypeMobile' => 'px',
                            'cntnfontSizeTypeTablet' => 'px',
                            'cntnfontSizeDesktop' => '',
                            'cntnfontSizeMobile' => '',
                            'cntnfontSizeTablet' => '',
                            'cntnlineHeight' => '',
                            'cntnlineHeightMobile' => '',
                            'cntnlineHeightTablet' => '',
                            'cntnletterSpacing' => '',
                            'cntnletterSpacingMobile' => '',
                            'cntnletterSpacingTablet' => '',
                            'cntnletterSpacingType' => 'px',
                            'cntnletterSpacingTypeTablet' => 'px',
                            'cntnletterSpacingTypeMobile' => 'px',
                            'cntntextTransform' => '',
                            'cntntextDecoration' => '',
                            'cntnfontStyle' => '',
                            'cntnTextColor' => '',
                            'titlePadding' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titlePaddingMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titlePaddingTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleMargin' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleMarginMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleMarginTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleAlignment' => '',
                            'titleAlignmentMobile' => '',
                            'titleAlignmentTablet' => '',
                            'noticeTitleBgColor' => '',
                            'titleBorder' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderType' => '',
                            'titleBorderMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderRadius' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderRadiusMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderRadiusTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorder' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderRadius' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderRadiusMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderRadiusTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderColor' => '',
                            'cntnBorderColor' => '',
                            'cntnAlignment' => '',
                            'cntnAlignmentMobile' => '',
                            'cntnAlignmentTablet' => '',
                            'cntnBorderType' => '',
                            'cntnMargin' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnMarginMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnMarginTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnPadding' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnPaddingMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnPaddingTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBgColor' => '',
                            'boxShadow' => [
                                'openShadow' => true, 'blur' => 35, 'color' => "rgba(0, 0, 0, 0.14)", 'horizontal' => 0,
                                'inset' => '', 'spread' => 0, 'vertical' => 8
                            ],
                        ),
                    ),
                    'affiliate-booster/ab-advance-button' => array(
                        'slug' => '',
                        'title' => __('Button', AFB_DOMAIN),
                        'description' => __('Showcase Button', AFB_DOMAIN),
                        'default' => true,
                        'attributes' => array(
                            'block_id' => '',
                            'btnTitle' => '',
                            'btnBg' => ['openBg' => false],
                            'btnBgHover' => ['openBg' => false],
                            'btnShadow' => [
                                'openShadow' => true, 'blur' => 35, 'color' => "rgba(0, 0, 0, 0.14)", 'horizontal' => 0,
                                'inset' => '', 'spread' => 0, 'vertical' => 8
                            ],
                            'titleTag1' => 'p',
                            'titleTag2' => 'p',
                            'titleLoadGoogleFonts' => '',
                            'titleTextColor' => '',
                            'titlefontFamily' => '',
                            'titlefontWeight' => '',
                            'titlefontSubset' => '',
                            'titlefontSizeType' => 'px',
                            'titlefontSizeTypeMobile' => 'px',
                            'titlefontSizeTypeTablet' => 'px',
                            'titlefontSizeDesktop' => '',
                            'titlefontSizeMobile' => '',
                            'titlefontSizeTablet' => '',
                            'titlelineHeight' => '',
                            'titlelineHeightMobile' => '',
                            'titlelineHeightTablet' => '',
                            'titleletterSpacing' => '',
                            'titleletterSpacingMobile' => '',
                            'titleletterSpacingTablet' => '',
                            'titleletterSpacingType' => 'px',
                            'titleletterSpacingTypeTablet' => 'px',
                            'titleletterSpacingTypeMobile' => 'px',
                            'titletextTransform' => '',
                            'titletextDecoration' => '',
                            'titlefontStyle' => '',
                            'titlePadding' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titlePaddingMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titlePaddingTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleMargin' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleMarginMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleMarginTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleAlignment' => '',
                            'titleAlignmentMobile' => '',
                            'titleAlignmentTablet' => '',
                            'titleBorder' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderType' => '',
                            'titleBorderMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderRadius' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderRadiusMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderRadiusTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'titleBorderColor' => '#F9CC29',
                            'btnBgColor' => '#F9CC29',
                            'titleBorderHoverColor' => '#61ce70',
                            'btnBgHoverColor' => '#00ffcc',
                            'titleTextHoverColor' => '#000000',
                            'btnHref' => '',
                            'boxShadow' => [
                                'openShadow' => true, 'blur' => 35, 'color' => "rgba(0, 0, 0, 0.14)", 'horizontal' => 0,
                                'inset' => '', 'spread' => 0, 'vertical' => 8
                            ],
                        ),
                    ),
                    'affiliate-booster/ab-notification-box' => array(
                        'slug' => '',
                        'title' => __('Notification Box', AFB_DOMAIN),
                        'description' => __('Showcase Button', AFB_DOMAIN),
                        'default' => true,
                        'attributes' => array(
                            'block_id' => '',
                            'noticeContent' => '',
                            'cntnLoadGoogleFonts' => '',
                            'cntnfontFamily' => '',
                            'titleTag1' => 'p',
                            'titleTag2' => 'p',
                            'cntnfontWeight' => '',
                            'cntnfontSubset' => '',
                            'cntnfontSizeType' => 'px',
                            'cntnfontSizeTypeMobile' => 'px',
                            'cntnfontSizeTypeTablet' => 'px',
                            'cntnfontSizeDesktop' => '',
                            'cntnfontSizeMobile' => '',
                            'cntnfontSizeTablet' => '',
                            'cntnlineHeight' => '',
                            'cntnlineHeightMobile' => '',
                            'cntnlineHeightTablet' => '',
                            'cntnletterSpacing' => '',
                            'cntnletterSpacingMobile' => '',
                            'cntnletterSpacingTablet' => '',
                            'cntnletterSpacingType' => 'px',
                            'cntnletterSpacingTypeTablet' => 'px',
                            'cntnletterSpacingTypeMobile' => 'px',
                            'cntntextTransform' => '',
                            'cntntextDecoration' => '',
                            'cntnfontStyle' => '',
                            'cntnTextColor' => '#000000',
                            'cntnBorder' => ['top' => '2', 'right' => '2', 'bottom' => '2', 'left' => '2', 'unit' => 'px'],
                            'cntnBorderMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderRadius' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderRadiusMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderRadiusTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBorderColor' => '#e9df9a',
                            'cntnAlignment' => '',
                            'cntnAlignmentMobile' => '',
                            'cntnAlignmentTablet' => '',
                            'cntnBorderType' => 'solid',
                            'cntnMargin' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnMarginMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnMarginTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnPadding' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnPaddingMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnPaddingTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'cntnBgColor' => '#fff5b3',
                            'customWidthType' => '%',
                            'customWidthTypeMobile' => '%',
                            'customWidthTypeTablet' => '%',
                            'customWidth' => '',
                            'customWidthMobile' => '',
                            'customWidthTablet' => '',
                            'boxShadow' => [
                                'openShadow' => true, 'blur' => 35, 'color' => "rgba(0, 0, 0, 0.14)", 'horizontal' => 0,
                                'inset' => '', 'spread' => 0, 'vertical' => 8
                            ],
                        ),
                    ),                    
                    'affiliate-booster/ab-callto-action' => array(
                        'slug' => '',
                        'title' => __('Call to action', AFB_DOMAIN),
                        'description' => __('Showcase Post title', AFB_DOMAIN),
                        'default' => true,
                        'attributes' => array(
                            'block_id' => '',
                            'boxBg' => ['openBg' => false],
                            'btnBg' => ['openBg' => false],
                            'btnBgHover' => ['openBg' => false],
                            'btnShadow' => [
                                'openShadow' => true, 'blur' => 35, 'color' => "rgba(0, 0, 0, 0.14)", 'horizontal' => 0,
                                'inset' => '', 'spread' => 0, 'vertical' => 8
                            ],
                            'ctaTitle' => '',
                            'titleLoadGoogleFonts' => '',
                            'ctaBtnText' => '',
                            'ctaContent' => '',
                            'ctaBtnHref' => '',
                            'titleTextColor' => '',
                            'titlefontFamily' => '',
                            'titlefontWeight' => '900',
                            'titlefontSubset' => '',
                            'titlefontSizeType' => 'px',
                            'titlefontSizeTypeMobile' => 'px',
                            'titlefontSizeTypeTablet' => 'px',
                            'titlefontSizeDesktop' => '36',
                            'titlefontSizeMobile' => '',
                            'titlefontSizeTablet' => '',
                            'titlelineHeight' => '',
                            'titlelineHeightMobile' => '',
                            'titlelineHeightTablet' => '',
                            'titleletterSpacing' => '',
                            'titleletterSpacingMobile' => '',
                            'titleletterSpacingTablet' => '',
                            'titleletterSpacingType' => 'px',
                            'titleletterSpacingTypeTablet' => 'px',
                            'titleletterSpacingTypeMobile' => 'px',
                            'titletextTransform' => '',
                            'titletextDecoration' => '',
                            'titlefontStyle' => '',
                            'btnLoadGoogleFonts' => '',
                            'btnfontFamily' => '',
                            'btnfontWeight' => '',
                            'btnfontSubset' => '',
                            'btnfontSizeType' => 'px',
                            'btnfontSizeTypeMobile' => 'px',
                            'btnfontSizeTypeTablet' => 'px',
                            'btnfontSizeDesktop' => '',
                            'btnfontSizeMobile' => '',
                            'btnfontSizeTablet' => '',
                            'btnlineHeight' => '',
                            'btnlineHeightMobile' => '',
                            'btnlineHeightTablet' => '',
                            'btnletterSpacing' => '',
                            'btnletterSpacingMobile' => '',
                            'btnletterSpacingTablet' => '',
                            'btnletterSpacingType' => 'px',
                            'btnletterSpacingTypeTablet' => 'px',
                            'btnletterSpacingTypeMobile' => 'px',
                            'btntextTransform' => '',
                            'btntextDecoration' => '',
                            'btnfontStyle' => '',
                            'btnBgColor' => '#F9CC29',
                            'btnHoverBgColor' => '#00ffcc',
                            'btnTextColor' => '#000000',
                            'btnTextHoverColor' => '#000000',
                            'btnBorderColor' => '#61ce70',
                            'btnBorderHoverColor' => '#F9CC29',
                            'btn_Htarget' => '',
                            'cntnLoadGoogleFonts' => '',
                            'cntnfontFamily' => '',
                            'cntnfontWeight' => '',
                            'cntnfontSubset' => '',
                            'cntnfontSizeType' => 'px',
                            'cntnfontSizeTypeMobile' => 'px',
                            'cntnfontSizeTypeTablet' => 'px',
                            'cntnfontSizeDesktop' => '',
                            'cntnfontSizeMobile' => '',
                            'cntnfontSizeTablet' => '',
                            'cntnlineHeight' => '',
                            'cntnlineHeightMobile' => '',
                            'cntnlineHeightTablet' => '',
                            'cntnletterSpacing' => '',
                            'cntnletterSpacingMobile' => '',
                            'cntnletterSpacingTablet' => '',
                            'cntnletterSpacingType' => 'px',
                            'cntnletterSpacingTypeTablet' => 'px',
                            'cntnletterSpacingTypeMobile' => 'px',
                            'cntntextTransform' => '',
                            'cntntextDecoration' => '',
                            'cntnfontStyle' => '',
                            'cntnTextColor' => '',
                            'boxPadding' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxPaddingMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxPaddingTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnPadding' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnPaddingMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnPaddingTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnMargin' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnMarginMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnMarginTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxMargin' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxMarginMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxMarginTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxAlignment' => 'center',
                            'boxAlignmentMobile' => 'center',
                            'boxAlignmentTablet' => 'center',
                            'boxStyle' => 'box-style-1',
                            'btnBorderType' => '',
                            'btnAlignment' => 'center',
                            'btnAlignmentMobile' => 'center',
                            'btnAlignmentTablet' => 'center',
                            'titleTag1' => 'p',
                            'titleTag2' => 'p',
                            'btnBorder' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderRadius' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderRadiusMobile' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'btnBorderRadiusTablet' => ['top' => '', 'right' => '', 'bottom' => '', 'left' => '', 'unit' => 'px'],
                            'boxShadow' => [
                                'openShadow' => true, 'blur' => 35, 'color' => "rgba(0, 0, 0, 0.14)", 'horizontal' => 0,
                                'inset' => '', 'spread' => 0, 'vertical' => 8
                            ],
                            'boxBorderType' => '',
                            'boxBorderColor' => '#006fbf',
                            'boxBorderWidth' => ['top' => 8, 'right' => 8, 'bottom' => 8, 'left' => 8, 'unit' => 'px'], 
                            'bgOverlay' => '',
                        ),
                    ),

                );
            }
            return self::$block_attributes;
        }

        /**
         * Get Block Assets.
         *
         * @since 1.13.4
         *
         * @return array The Asset List.
         */
        public static function get_block_assets()
        {

            if (null === self::$block_assets) {
                self::$block_assets = array(
                    /*'affiliate-table-of-contents' => array(
                        'src' => AFB_URL . 'dist/assets/js/toc.js',
                        'dep' => array('jquery'),
                    ),*/
                );
            }
            return self::$block_assets;
        }
    }
}
